[package]
name = "yew-limput"
version = "0.1.0"
edition = "2024"
authors = ["Sean Bruton <sean@>"]

[dependencies]
tracing = "0.1.41"
web-sys = { version = "0.3.77", features = ["HtmlInputElement"] }
yew = "0.21.0"
