[package]
name = "yew-limput-example-text"
version = "0.2.0"
edition = "2024"
authors = ["Sean Bruton <sean@seanbruton.dev>"]

[dependencies]
tracing = "0.1.41"
tracing-wasm = "0.2.1"
yew = { version = "0.21.0", features = ["csr"] }
yew-limput = { path = "../../" }
